### ISSUE TITLE
sqlalchemy 1.3.24 issues

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/healpix-alchemy#29]
With sqlalchemy 1.3.24, I get for the second line of the percentile query:

            subquery1 = (
                sa.select(LocalizationTile.probdensity, cum_prob).filter(
                    LocalizationTile.localization_id == localization.id
                )
            ).subquery()

The below. Should this already be compatible?

```pytb
Traceback (most recent call last):
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/mcoughlin/Code/ZTF/skyportal-branches/crossmatch2/skyportal/baselayer/app/access.py", line 37, in wrapper
    return tornado.web.authenticated(method)(self, *args, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/mcoughlin/Code/ZTF/skyportal-branches/crossmatch2/skyportal/skyportal/handlers/api/source.py", line 1097, in get
    sa.select(LocalizationTile.probdensity, cum_prob).filter(
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 3117, in __init__
    for c in columns:
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 226, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/orm/properties.py", line 367, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 762, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "<string>", line 1, in <lambda>
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 68, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/default_comparator.py", line 237, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/default_comparator.py", line 241, in _unsupported_impl
    raise NotImplementedError(
NotImplementedError: Operator 'getitem' is not supported on this expression
```

**Comment by lpsinger** [comment]
I cannot reproduce this: when I set `sqlalchemy = "==1.3.24"` in my pyproject.toml file, run `poetry update`, and run `pytest`, everything passes.

Do you have a minimal example to reproduce this error?

**Comment by mcoughlin** [comment]
i guess yours is the minimal example but clearly something is going wrong. I don't know how to fix it.

**Comment by lpsinger** [comment]
What is the type of `localization.id`?

**Comment by mcoughlin** [comment]
It's baselayer's usual id in the Base class. https://github.com/cesium-ml/baselayer/blob/master/app/models.py. I think they are just Strings? @acrellin ?

**Comment by acrellin** [comment]
The base class's `id` column is an auto-incremented integer.

**Comment by acrellin** [comment]
Where does this `localization` instance come from?

**Comment by mcoughlin** [comment]
localization = (
                    Localization.query_records_accessible_by(self.current_user)
                    .filter(Localization.dateobs == localization_dateobs)
                    .filter(Localization.localization_name == localization_name)
                    .first()

Just a query
